version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user_password
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  inception:

# mounted at run time
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt