#version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    image: inception-mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_user_password
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: inception-wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_user_password
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:

# mounted at run time
secrets:
  db_user_password:
    file: ../secrets/db_user_password.txt