server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # for wordpress
    root /var/www/html;
    index index.php index.html;

    # wordPress routing
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # PHP files handling (send to PHP-FPM)
    location ~ \.php$ {
        include fastcgi_params;

        # Browser → Nginx (port 443) → WordPress/PHP-FPM (port 9000) → MariaDB (port 3306)
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Deny access to hidden files (like .env)
    location ~ /\. {
        deny all;
    }
}
